meeting:
  - "Team sync‑up meeting"
  - "Project planning meeting"
announcement:
  - "Official announcement"
  - "Please note the announcement"
internship:
  - "Summer internship opportunity"
  - "Apply for internship"
  - "Internship application deadline"
  - "Internship program details"
  - "Registration deadline for the internship"
  - "Exchange program opportunity"
  - "exchange program"
club:
  - "Student club event"
  - "Join our club"
  - "Club orientations"
  - "Sunshine meeting invites"
  - "shuffle conducting events"
  - "Vibes conducting events"
  - "milan events"
  - "Elan and nvision"
  - "Diesta events"
  - "Behind the lens events"
talks:
  - "Guest speaker talk"
  - "Research seminar talks"
  - "Invitation for seminar"
  - "viva voice"
  - "Upcoming talks"
  - "Research talks"
  - "Sessions on academics"
  - "Upcoming events"
  - "Event registration"
  - "Invitation to event"
maintenance:
  - "scheduled maintenance"
  - "Maintenance window"
  - "Internet connection down"
  - "Shutdown notice"
academics:
  - "Academic calendar"
  - "Course registration"
  - "Exam schedule"
  - "Assignment deadlines"
  - "Assignment submission"
