name: Trigger auto deployment for email-classifier

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/email-classifier-AutoDeployTrigger-907d1249-a6a3-4019-95e0-c39f992b71ae.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMAILCLASSIFIER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EMAILCLASSIFIER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EMAILCLASSIFIER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.EMAILCLASSIFIER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMAILCLASSIFIER_REGISTRY_PASSWORD }}
          containerAppName: email-classifier
          resourceGroup: skgezhil-container
          imageToBuild: skgezhil/email-classifier:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


